server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: false

logging:
  level:
    com.fastpos: INFO
